Use boto session to avoid multithreading error
PokaInc/django-ses-boto3 pull request #1
Opened 2018-10-31 13:45 UTC by alexandredufour

Use boto session instead of directly call `client` to avoid multithreading error.
https://sentry.io/poka-inc/prod-backend/issues/732308515/

PS: I've replicated what we're using in Poka 
PPS: Before merging this PR, this must be tested on a dev instance

2018-10-31 13:48 UTC, raphael-riel approved these changes

2018-10-31 13:50 UTC, tea-rudolf approved these changes

2018-11-01 13:56 UTC, Asylvestre requested changes
Other then that lgtm

2018-11-01 13:56 UTC, Asylvestre commented on django_ses_boto3/ses_email_backend.py
> +
One blank line too many

2018-11-01 13:56 UTC, Asylvestre commented on django_ses_boto3/ses_email_backend.py
> +        return session
missing end of the file new line

2018-11-01 13:56 UTC, Asylvestre commented on django_ses_boto3/ses_email_backend.py
> +
Missing a line jump

2018-11-01 14:05 UTC, Asylvestre approved these changes

2018-11-01 14:05 UTC, merged